name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.17' ]
    name: Build for Go ${{ matrix.go }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
